import type { DevelopmentLevel } from "./types"

/**
 * Mock data for Ciclo de Formação.
 * Replace with Supabase queries when integrating.
 */
export const MOCK_DEVELOPMENT_LEVELS: DevelopmentLevel[] = [
  {
    id: "level-qualify",
    slug: "qualify",
    name: "Qualify",
    description: "Etapa inicial de formação - conhecendo o IFL e seus valores",
    orderIndex: 0,
    tasks: [
      {
        id: "task-q-1",
        title: "Assistir ao vídeo de boas-vindas",
        description: "Conheça a história e missão do IFL Jovem",
        taskType: "link",
        contentUrl: "https://www.youtube.com/watch?v=example",
        orderIndex: 0,
      },
      {
        id: "task-q-2",
        title: "Leitura do estatuto",
        description: "Leia o estatuto do instituto (PDF)",
        taskType: "file",
        contentUrl: "/documents/estatuto-ifl.pdf",
        orderIndex: 1,
      },
      {
        id: "task-q-3",
        title: "Foto de perfil institucional",
        description: "Envie foto para o cadastro (fundo neutro)",
        taskType: "image",
        contentUrl: "/placeholder-image.jpg",
        orderIndex: 2,
      },
    ],
  },
  {
    id: "level-associado-i",
    slug: "associado_i",
    name: "Associado I",
    description: "Desenvolvimento das competências básicas de liderança",
    orderIndex: 1,
    tasks: [
      {
        id: "task-a1-1",
        title: "Curso de Liderança Básica",
        description: "Complete o curso online de fundamentos de liderança",
        taskType: "link",
        contentUrl: "https://example.com/curso-lideranca",
        orderIndex: 0,
      },
      {
        id: "task-a1-2",
        title: "Relatório de participação",
        description: "Modelo de relatório das atividades do semestre",
        taskType: "file",
        contentUrl: "/documents/modelo-relatorio.docx",
        orderIndex: 1,
      },
      {
        id: "task-a1-3",
        title: "Apresentação de projeto",
        description: "Template para apresentação de projetos",
        taskType: "image",
        contentUrl: "/images/template-apresentacao.png",
        orderIndex: 2,
      },
      {
        id: "task-a1-4",
        title: "Palestra: Comunicação Assertiva",
        description: "Gravação da palestra sobre comunicação",
        taskType: "link",
        contentUrl: "https://vimeo.com/example",
        orderIndex: 3,
      },
    ],
  },
  {
    id: "level-associado-ii",
    slug: "associado_ii",
    name: "Associado II",
    description: "Aprofundamento em gestão de times e projetos",
    orderIndex: 2,
    tasks: [
      {
        id: "task-a2-1",
        title: "Workshop de Gestão de Projetos",
        description: "Material complementar do workshop",
        taskType: "file",
        contentUrl: "/documents/workshop-gestao.pdf",
        orderIndex: 0,
      },
      {
        id: "task-a2-2",
        title: "Canal de cases de sucesso",
        description: "Biblioteca de casos e boas práticas",
        taskType: "link",
        contentUrl: "https://notion.so/example-cases",
        orderIndex: 1,
      },
      {
        id: "task-a2-3",
        title: "Diagrama de competências",
        description: "Mapa visual das competências por nível",
        taskType: "image",
        contentUrl: "/images/mapa-competencias.png",
        orderIndex: 2,
      },
      {
        id: "task-a2-4",
        title: "Guia de feedback 360°",
        description: "Como aplicar avaliação 360° no seu time",
        taskType: "file",
        contentUrl: "/documents/guia-feedback-360.pdf",
        orderIndex: 3,
      },
      {
        id: "task-a2-5",
        title: "Webinar: Liderança Situacional",
        description: "Assista à gravação do webinar",
        taskType: "link",
        contentUrl: "https://youtube.com/example-webinar",
        orderIndex: 4,
      },
    ],
  },
  {
    id: "level-associado-senior",
    slug: "associado_senior",
    name: "Associado Sênior",
    description: "Mentoria, estratégia e desenvolvimento de líderes",
    orderIndex: 3,
    tasks: [
      {
        id: "task-as-1",
        title: "Guia de Mentoria",
        description: "Metodologia oficial de mentoria IFL",
        taskType: "file",
        contentUrl: "/documents/guia-mentoria.pdf",
        orderIndex: 0,
      },
      {
        id: "task-as-2",
        title: "Plataforma de estratégia",
        description: "Ferramentas de planejamento estratégico",
        taskType: "link",
        contentUrl: "https://strategy.ifl.org",
        orderIndex: 1,
      },
      {
        id: "task-as-3",
        title: "Certificado de conclusão",
        description: "Modelo de certificado para eventos",
        taskType: "image",
        contentUrl: "/images/modelo-certificado.png",
        orderIndex: 2,
      },
      {
        id: "task-as-4",
        title: "Pesquisa de satisfação",
        description: "Formulário para avaliar eventos e formações",
        taskType: "link",
        contentUrl: "https://forms.gle/example",
        orderIndex: 3,
      },
      {
        id: "task-as-5",
        title: "Apresentação executiva",
        description: "Template para apresentações à diretoria",
        taskType: "file",
        contentUrl: "/documents/apresentacao-executiva.pptx",
        orderIndex: 4,
      },
    ],
  },
]
